language: node_js
node_js:
  - "6.9"
env:
  - NODE_ENV=production
before_deploy:
  - "webpack --config webpack.config.production.js"
deploy:
  provider: surge
  project: ./build
  domain: vulpine.me
  skip_cleanup: true
